/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import entidades.Curso;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import servicios.Conexion;

/**
 *
 * @author miran
 */
public class AgregarCurso extends javax.swing.JDialog {
    
    Conexion conn = new Conexion();
    
    
    /**
     * Creates new form agregarCurso
     */
    public AgregarCurso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        rbLunes = new javax.swing.JRadioButton();
        rbMartes = new javax.swing.JRadioButton();
        rbMier = new javax.swing.JRadioButton();
        rbJuev = new javax.swing.JRadioButton();
        rbVier = new javax.swing.JRadioButton();
        rbSab = new javax.swing.JRadioButton();
        cbPeriodo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Periodo");

        jLabel3.setText("Dias");

        jLabel4.setText("Hora");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        rbLunes.setText("Lunes");
        rbLunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLunesActionPerformed(evt);
            }
        });

        rbMartes.setText("Martes");

        rbMier.setText("Miércoles");

        rbJuev.setText("Jueves");

        rbVier.setText("Viernes");

        rbSab.setText("Sábado");

        cbPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AgoDic20", "EneJun21", "AgoDic21", "EneJun22" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbMier)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbSab))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbMartes)
                                    .addComponent(rbLunes))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbVier)
                                    .addComponent(rbJuev)))
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btnAgregar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbLunes)
                    .addComponent(rbJuev)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMartes)
                    .addComponent(rbVier))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMier)
                    .addComponent(rbSab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnAgregar)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String nombre = this.txtNombre.getText();
        String periodo = this.cbPeriodo.getSelectedItem().toString();
        
        String dias = "";
        if (this.rbLunes.isSelected())  dias +=  "Lu";     
        if (this.rbMartes.isSelected())  dias += "Ma";
        if (this.rbMier.isSelected()) dias += "Mi";
        if (this.rbJuev.isSelected()) dias += "Ju";
        if (this.rbVier.isSelected()) dias += "V";
        if (this.rbSab.isSelected()) dias += "Sab";
        
        String hora = this.txtHora.getText();
        
        boolean horaReg = Pattern.matches("^([01]?[0-9]|2[0-3]):[0-5][0-9]$", hora);
        
        if (horaReg){
            
            if ("".equals(dias) || periodo.isEmpty() || nombre.isEmpty()){
                JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos");
            } else {
                try {
                    //Aquí va lo para agregar
                    Curso curso = new Curso(nombre, periodo, dias, hora);
                    guardar(Conexion.obtener(), curso);
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(AgregarCurso.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Por favor rellene la hora con sistema de 24 horas");
        }
        
        
        
        
          
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void rbLunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLunesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLunesActionPerformed

    public void guardar(Connection conexion, Curso curso) throws SQLException{
      try{
         PreparedStatement consulta;
         
         if (conn.ifExists ("Select * from cursos where nombre = ? AND periodo = ? AND dias = ? AND hora = ?", 
                 curso.getNombre(), curso.getPeriodo(), curso.getDias(), curso.getHora())){
        //Existe registro
            JOptionPane.showMessageDialog(this, "El curso ya está registrado");
        }else{
        //No hay registros
            consulta = conexion.prepareStatement("INSERT INTO cursos (nombre, periodo, dias, hora) VALUES(?, ?, ?, ?);");
            consulta.setString(1, curso.getNombre());
            consulta.setString(2, curso.getPeriodo());
            consulta.setString(3, curso.getDias());
            consulta.setString(4, curso.getHora());
            consulta.executeUpdate();
            JOptionPane.showMessageDialog(this, "¡Se registró el curso con exito!");
        }
           
      }catch(SQLException ex){
          JOptionPane.showMessageDialog(this, "Error con el registro");
         throw new SQLException(ex);
      }
      
      
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbPeriodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbJuev;
    private javax.swing.JRadioButton rbLunes;
    private javax.swing.JRadioButton rbMartes;
    private javax.swing.JRadioButton rbMier;
    private javax.swing.JRadioButton rbSab;
    private javax.swing.JRadioButton rbVier;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
