/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import entidades.Curso;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import servicios.Conexion;

/**
 *
 * @author miran
 */
public class DlgAgregarCurso extends javax.swing.JDialog {
    
    Conexion conn = new Conexion();
    
    
    /**
     * Creates new form agregarCurso
     * @param parent
     * @param modal
     */
    public DlgAgregarCurso(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtHora = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        rbLunes = new javax.swing.JRadioButton();
        rbMartes = new javax.swing.JRadioButton();
        rbMier = new javax.swing.JRadioButton();
        rbJuev = new javax.swing.JRadioButton();
        rbVier = new javax.swing.JRadioButton();
        rbSab = new javax.swing.JRadioButton();
        cbPeriodo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Curso");

        jLabel1.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel2.setText("Periodo");

        jLabel3.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel3.setText("Dias");

        jLabel4.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jLabel4.setText("Hora");

        btnAgregar.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        rbLunes.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        rbLunes.setText("Lunes");
        rbLunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLunesActionPerformed(evt);
            }
        });

        rbMartes.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        rbMartes.setText("Martes");

        rbMier.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        rbMier.setText("Miércoles");

        rbJuev.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        rbJuev.setText("Jueves");

        rbVier.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        rbVier.setText("Viernes");

        rbSab.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        rbSab.setText("Sábado");

        cbPeriodo.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        cbPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AgoDic20", "EneJun21", "AgoDic21", "EneJun22" }));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel6.setText("Agregar hora con sistema de 24 hrs.");

        jButton1.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        jButton1.setText("Regresar");
        jButton1.setToolTipText("");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbMier)
                                    .addComponent(rbMartes)
                                    .addComponent(rbLunes))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbSab)
                                    .addComponent(rbVier)
                                    .addComponent(rbJuev)))
                            .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(33, 33, 33)
                                .addComponent(btnAgregar)))))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbLunes)
                            .addComponent(rbJuev))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbMartes)
                            .addComponent(rbVier))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbMier)
                            .addComponent(rbSab))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(jButton1))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String nombre = this.txtNombre.getText();
        String periodo = this.cbPeriodo.getSelectedItem().toString();
        
        String dias = "";
        if (this.rbLunes.isSelected())  dias +=  "Lu";     
        if (this.rbMartes.isSelected())  dias += "Ma";
        if (this.rbMier.isSelected()) dias += "Mi";
        if (this.rbJuev.isSelected()) dias += "Ju";
        if (this.rbVier.isSelected()) dias += "V";
        if (this.rbSab.isSelected()) dias += "Sab";
        
        String hora = this.txtHora.getText();
        
        boolean horaReg = Pattern.matches("^([01]?[0-9]|2[0-3]):[0-5][0-9]$", hora);
        
        if (horaReg){
            
            if ("".equals(dias) || periodo.isEmpty() || nombre.isEmpty()){
                JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos");
            } else {
                try {
                    //Aquí va lo para agregar
                    Curso curso = new Curso(nombre, periodo, dias, hora);
                    guardar(Conexion.obtener(), curso);
                    txtNombre.setText("");
                    txtHora.setText("");
                    rbLunes.setSelected(false);
                    rbMartes.setSelected(false);
                    rbMier.setSelected(false);
                    rbJuev.setSelected(false);
                    rbVier.setSelected(false);
                    rbSab.setSelected(false);
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(DlgAgregarCurso.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Por favor rellene la hora con sistema de 24 horas");
        }
        
               
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void rbLunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLunesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLunesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void guardar(Connection conexion, Curso curso) throws SQLException{
      try{
         PreparedStatement consulta;
         
         if (conn.ifExists ("Select * from cursos where nombre = ? AND periodo = ? AND dias = ? AND hora = ?", 
                 curso.getNombre(), curso.getPeriodo(), curso.getDias(), curso.getHora())){
        //Existe registro
            JOptionPane.showMessageDialog(this, "El curso ya está registrado");
        }else{
        //No hay registros
            consulta = conexion.prepareStatement("INSERT INTO cursos (nombre, periodo, dias, hora) VALUES(?, ?, ?, ?);");
            consulta.setString(1, curso.getNombre());
            consulta.setString(2, curso.getPeriodo());
            consulta.setString(3, curso.getDias());
            consulta.setString(4, curso.getHora());
            consulta.executeUpdate();
            JOptionPane.showMessageDialog(this, "¡Se registró el curso con exito!");
            //conexion.close();
            
        }
           
      }catch(SQLException ex){
          JOptionPane.showMessageDialog(this, "Error con el registro");
         throw new SQLException(ex);
      }
      
      
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbPeriodo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton rbJuev;
    private javax.swing.JRadioButton rbLunes;
    private javax.swing.JRadioButton rbMartes;
    private javax.swing.JRadioButton rbMier;
    private javax.swing.JRadioButton rbSab;
    private javax.swing.JRadioButton rbVier;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
