/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import entidades.Curso;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import servicios.Conexion;
import interfaces.Frprincipal;

        
/**
 *
 * @author miran
 */
public class DlgEditarCurso extends javax.swing.JDialog {

    private Curso curso;
     Conexion conn = new Conexion();
     ArrayList<String> periodos;
    /**
     * Creates new form DlgEditarCurso
     * @param parent
     * @param modal
     * @param curso
     * @param periodoSeleccionado
     */
    public DlgEditarCurso(java.awt.Frame parent, boolean modal, Curso curso) {
        super(parent, modal);
        initComponents();
        this.curso = curso;
        llenarCampos();
        setLocationRelativeTo(null);
    }
    
    public void llenarCampos(){
        txtNombre.setText(curso.getNombre());
        txtHora.setText(curso.getHora());
        
        periodos = new ArrayList();
        periodos.add("AgoDic20");
        periodos.add("EneJun21");
        periodos.add("AgoDic21");
        periodos.add("EneJun22");
        
        for(int i = 0; i < periodos.size(); i++){
            if(periodos.get(i).equals(curso.getPeriodo())){
                cbPeriodo.setSelectedIndex(i);
            }
        }
        
        String dias = curso.getDias();
        if(dias.contains("Lu"))
            rbLunes.setSelected(true);
        if(dias.contains("Ma"))
            rbMartes.setSelected(true);
        if(dias.contains("Mi"))
            rbMier.setSelected(true);
        if(dias.contains("Ju"))
            rbJuev.setSelected(true);
        if(dias.contains("V"))
            rbVier.setSelected(true);
        if(dias.contains("Sab"))
            rbSab.setSelected(true);
        
    }
    
    
    public void guardar(Connection conexion, Curso cursoNuevo) throws SQLException {
        try {
            PreparedStatement consulta;

            if (conn.ifExists("Select * from cursos where nombre = ? AND periodo = ? AND dias = ? AND hora = ?",
                    cursoNuevo.getNombre(), cursoNuevo.getPeriodo(), cursoNuevo.getDias(), cursoNuevo.getHora())) {
                //Existe registro
                JOptionPane.showMessageDialog(this, "Ya existe un curso con los mismos datos");
            } else {
                //No existe registro
                consulta = conexion.prepareStatement("UPDATE  cursos SET nombre = '" + cursoNuevo.getNombre()
                        + "', periodo = '" + cursoNuevo.getPeriodo()
                        + "', dias = '" + cursoNuevo.getDias()
                        + "', hora = '" + cursoNuevo.getHora()
                        + "' WHERE cursos.id = " + curso.getId() + ";");
                
                consulta.executeUpdate();
                JOptionPane.showMessageDialog(this, "¡Se actualizó el curso con exito!");
                this.setVisible(false);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error con el registro");
            throw new SQLException(ex);
        }

   }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        cbPeriodo = new javax.swing.JComboBox<>();
        rbLunes = new javax.swing.JRadioButton();
        rbMartes = new javax.swing.JRadioButton();
        rbMier = new javax.swing.JRadioButton();
        rbSab = new javax.swing.JRadioButton();
        rbVier = new javax.swing.JRadioButton();
        rbJuev = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lato", 1, 16)); // NOI18N
        jLabel1.setText("Nombre");

        jLabel2.setFont(new java.awt.Font("Lato", 1, 16)); // NOI18N
        jLabel2.setText("Periodo");

        jLabel3.setFont(new java.awt.Font("Lato", 1, 16)); // NOI18N
        jLabel3.setText("Dias");

        jLabel4.setFont(new java.awt.Font("Lato", 1, 16)); // NOI18N
        jLabel4.setText("Hora");

        txtNombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        cbPeriodo.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        cbPeriodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AgoDic20", "EneJun21", "AgoDic21", "EneJun22" }));
        cbPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPeriodoActionPerformed(evt);
            }
        });

        rbLunes.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        rbLunes.setText("Lunes");
        rbLunes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLunesActionPerformed(evt);
            }
        });

        rbMartes.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        rbMartes.setText("Martes");

        rbMier.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        rbMier.setText("Miércoles");

        rbSab.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        rbSab.setText("Sábado");

        rbVier.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        rbVier.setText("Viernes");

        rbJuev.setFont(new java.awt.Font("Lato", 0, 14)); // NOI18N
        rbJuev.setText("Jueves");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel6.setText("Agregar hora con sistema de 24 hrs.");

        txtHora.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnActualizar.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(75, 75, 75)
                        .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnActualizar))
                    .addComponent(jLabel6))
                .addGap(105, 105, 105))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(153, 153, 153)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbMier)
                                .addComponent(rbMartes)
                                .addComponent(rbLunes))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbSab)
                                .addComponent(rbVier)
                                .addComponent(rbJuev))))
                    .addContainerGap(65, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(97, 97, 97)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnCancelar))
                .addGap(37, 37, 37))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(30, 30, 30)
                    .addComponent(cbPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbLunes)
                        .addComponent(rbJuev))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbMartes)
                        .addComponent(rbVier))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbMier)
                        .addComponent(rbSab))
                    .addContainerGap(178, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbLunesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLunesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLunesActionPerformed

    private void cbPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPeriodoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPeriodoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        String nombre = this.txtNombre.getText();
        String periodo = this.cbPeriodo.getSelectedItem().toString();
        
        String dias = "";
        if (this.rbLunes.isSelected())  dias +=  "Lu";     
        if (this.rbMartes.isSelected())  dias += "Ma";
        if (this.rbMier.isSelected()) dias += "Mi";
        if (this.rbJuev.isSelected()) dias += "Ju";
        if (this.rbVier.isSelected()) dias += "V";
        if (this.rbSab.isSelected()) dias += "Sab";
        
        String hora = this.txtHora.getText();
        
        boolean horaReg = Pattern.matches("^([01]?[0-9]|2[0-3]):[0-5][0-9]$", hora);
        
        if (horaReg){
            
            if ("".equals(dias) || periodo.isEmpty() || nombre.isEmpty()){
                JOptionPane.showMessageDialog(this, "Por favor rellene todos los campos");
            } else {
                try {
                    
                    //Aquí va lo para agregar
                    Curso cursin = new Curso(nombre, periodo, dias, hora);
                    guardar(Conexion.obtener(), cursin);
                    
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(DlgAgregarCurso.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "Por favor rellene la hora con sistema de 24 horas");
        }
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JComboBox<String> cbPeriodo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton rbJuev;
    private javax.swing.JRadioButton rbLunes;
    private javax.swing.JRadioButton rbMartes;
    private javax.swing.JRadioButton rbMier;
    private javax.swing.JRadioButton rbSab;
    private javax.swing.JRadioButton rbVier;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
