/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;
/**
 *
 * @author miran
 */



public class Frprincipal extends javax.swing.JFrame {

    DlgAgregarCurso agregarC;
    DlgListarCursos listarC;
    DlgDatos datosC;
    /**
     * Creates new form frprincipal
     */
    public Frprincipal() {
        initComponents();
        this.setSize(375, 473);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarCurso = new javax.swing.JButton();
        btnListarCursos = new javax.swing.JButton();
        txtLogo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregarCurso.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        agregarCurso.setText("Agregar curso");
        agregarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarCursoActionPerformed(evt);
            }
        });
        getContentPane().add(agregarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 170, -1));

        btnListarCursos.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        btnListarCursos.setText("Cursos registrados");
        btnListarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarCursosActionPerformed(evt);
            }
        });
        getContentPane().add(btnListarCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 170, -1));

        txtLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo.png"))); // NOI18N
        getContentPane().add(txtLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 280, 160));

        jButton1.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jButton1.setText("Importar asistencias");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 170, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarCursoActionPerformed
        // TODO add your handling code here:
        agregarC = new DlgAgregarCurso(this, true);
        agregarC.setVisible(true);
    }//GEN-LAST:event_agregarCursoActionPerformed

    private void btnListarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarCursosActionPerformed
        // TODO add your handling code here:
        listarC = new DlgListarCursos(this, true);
        listarC.setVisible(true);
    }//GEN-LAST:event_btnListarCursosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        datosC = new DlgDatos();
        datosC.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frprincipal().setVisible(true);
            }
        });
    }
    
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarCurso;
    private javax.swing.JButton btnListarCursos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel txtLogo;
    // End of variables declaration//GEN-END:variables
}
