/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;
/**
 *
 * @author miran
 */



public class Frprincipal extends javax.swing.JFrame {

    DlgAgregarCurso agregarC;
    DlgListarCursos listarC;
    DlgDatos datosC;
    DlgConsultarAsistencias consultarA;
    DlgCambiar cambi;
    DlgAgregarUnidad agregarU;
    DlgConsultarUnidades consultarU;
    DlgConsultarAsistenciaUnidades consultarAsisUni;
    DlgConsultarAsistencias2 consultarAsis2;
    /**
     * Creates new form frprincipal
     */
    public Frprincipal() {
        initComponents();
       this.setSize(565, 410);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        txtLogo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miNuevoCurso = new javax.swing.JMenuItem();
        miCursosRegistrados = new javax.swing.JMenuItem();
        Asistencias = new javax.swing.JMenu();
        miImportar = new javax.swing.JMenuItem();
        miConsultarAsis = new javax.swing.JMenuItem();
        miModificar = new javax.swing.JMenuItem();
        miConsultarAsisUnidad = new javax.swing.JMenuItem();
        miConsultarTotal = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        miAgregarUnidad = new javax.swing.JMenuItem();
        miConsultarUnidades = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo2.png"))); // NOI18N
        getContentPane().add(txtLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 400, 190));

        jLabel1.setFont(new java.awt.Font("Lato", 0, 18)); // NOI18N
        jLabel1.setText("Sistema para manejar los cursos virtuales");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/174675.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jMenu1.setText("Cursos");
        jMenu1.setFont(new java.awt.Font("Lato", 1, 16)); // NOI18N

        miNuevoCurso.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        miNuevoCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton-agregar.png"))); // NOI18N
        miNuevoCurso.setText("Agregar nuevo");
        miNuevoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNuevoCursoActionPerformed(evt);
            }
        });
        jMenu1.add(miNuevoCurso);

        miCursosRegistrados.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        miCursosRegistrados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consultar.png"))); // NOI18N
        miCursosRegistrados.setText("Consultar");
        miCursosRegistrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCursosRegistradosActionPerformed(evt);
            }
        });
        jMenu1.add(miCursosRegistrados);

        jMenuBar1.add(jMenu1);

        Asistencias.setText("Asistencias");
        Asistencias.setFont(new java.awt.Font("Lato", 1, 16)); // NOI18N

        miImportar.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        miImportar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton-agregar.png"))); // NOI18N
        miImportar.setText("Importar lista");
        miImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miImportarActionPerformed(evt);
            }
        });
        Asistencias.add(miImportar);

        miConsultarAsis.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        miConsultarAsis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consultar.png"))); // NOI18N
        miConsultarAsis.setText("Consultar");
        miConsultarAsis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultarAsisActionPerformed(evt);
            }
        });
        Asistencias.add(miConsultarAsis);

        miModificar.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        miModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/modificar.png"))); // NOI18N
        miModificar.setText("Modificar");
        miModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miModificarActionPerformed(evt);
            }
        });
        Asistencias.add(miModificar);

        miConsultarAsisUnidad.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        miConsultarAsisUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consultar.png"))); // NOI18N
        miConsultarAsisUnidad.setText("Consultar por unidad");
        miConsultarAsisUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultarAsisUnidadActionPerformed(evt);
            }
        });
        Asistencias.add(miConsultarAsisUnidad);

        miConsultarTotal.setFont(new java.awt.Font("Lato", 1, 14)); // NOI18N
        miConsultarTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consultar.png"))); // NOI18N
        miConsultarTotal.setText("Consultar total");
        miConsultarTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultarTotalActionPerformed(evt);
            }
        });
        Asistencias.add(miConsultarTotal);

        jMenuBar1.add(Asistencias);

        jMenu3.setText("Unidades");
        jMenu3.setFont(new java.awt.Font("Lato", 1, 16)); // NOI18N

        miAgregarUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton-agregar.png"))); // NOI18N
        miAgregarUnidad.setText("Agregar");
        miAgregarUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAgregarUnidadActionPerformed(evt);
            }
        });
        jMenu3.add(miAgregarUnidad);

        miConsultarUnidades.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/consultar.png"))); // NOI18N
        miConsultarUnidades.setText("Consultar");
        miConsultarUnidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultarUnidadesActionPerformed(evt);
            }
        });
        jMenu3.add(miConsultarUnidades);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCursosRegistradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCursosRegistradosActionPerformed
        // TODO add your handling code here:
        listarC = new DlgListarCursos(this, true);
        listarC.setVisible(true);
    }//GEN-LAST:event_miCursosRegistradosActionPerformed

    private void miConsultarAsisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarAsisActionPerformed
        // TODO add your handling code here:
        consultarA = new DlgConsultarAsistencias(this, true);
        consultarA.setVisible(true);
    }//GEN-LAST:event_miConsultarAsisActionPerformed

    private void miImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miImportarActionPerformed
        // TODO add your handling code here:
        datosC = new DlgDatos();
        datosC.setVisible(true);
    }//GEN-LAST:event_miImportarActionPerformed

    private void miModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miModificarActionPerformed
        // TODO add your handling code here:
        cambi = new DlgCambiar(this, true);
        cambi.setVisible(true);
    }//GEN-LAST:event_miModificarActionPerformed

    private void miNuevoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNuevoCursoActionPerformed
        // TODO add your handling code here:
        agregarC = new DlgAgregarCurso(this, true);
        agregarC.setVisible(true);
    }//GEN-LAST:event_miNuevoCursoActionPerformed

    private void miAgregarUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAgregarUnidadActionPerformed
        // TODO add your handling code here:
        agregarU = new DlgAgregarUnidad(this, true);
        agregarU.setVisible(true);
    }//GEN-LAST:event_miAgregarUnidadActionPerformed

    private void miConsultarUnidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarUnidadesActionPerformed
        // TODO add your handling code here:
            consultarU = new DlgConsultarUnidades(this, true);
            consultarU.setVisible(true);
    }//GEN-LAST:event_miConsultarUnidadesActionPerformed

    private void miConsultarAsisUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarAsisUnidadActionPerformed
        // TODO add your handling code here:
        consultarAsisUni = new DlgConsultarAsistenciaUnidades(this, true);
        consultarAsisUni.setVisible(true);
    }//GEN-LAST:event_miConsultarAsisUnidadActionPerformed

    private void miConsultarTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultarTotalActionPerformed
        // TODO add your handling code here:
        consultarAsis2 = new DlgConsultarAsistencias2(this, true);
        consultarAsis2.setVisible(true);
    }//GEN-LAST:event_miConsultarTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frprincipal().setVisible(true);
            }
        });
    }
    
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Asistencias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JMenuItem miAgregarUnidad;
    private javax.swing.JMenuItem miConsultarAsis;
    private javax.swing.JMenuItem miConsultarAsisUnidad;
    private javax.swing.JMenuItem miConsultarTotal;
    private javax.swing.JMenuItem miConsultarUnidades;
    private javax.swing.JMenuItem miCursosRegistrados;
    private javax.swing.JMenuItem miImportar;
    private javax.swing.JMenuItem miModificar;
    private javax.swing.JMenuItem miNuevoCurso;
    private javax.swing.JLabel txtLogo;
    // End of variables declaration//GEN-END:variables
}
